spring:
  application:
    name: todoistapp

  datasource:
    url: jdbc:mysql://mysql:3306/todoist?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME:todo}
    password: ${SPRING_DATASOURCE_PASSWORD:todo_pwd}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}



app:
  webclient:
    callapp2: ${APP_WEBCLIENT_CALLAPP2:http://adminapp:8080/hello}
  redis:
    enabled: true
#logging:
#  level:
#    root: INFO